# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  pool: 5
  username: 'root'
  password: 'root'
  timeout: 5000
  host: 127.0.0.1

development:
  <<: *default
  database: api_development
production:
  <<: *default
  database: api_production
